### ISSUE TITLE
Quick Start Not Working - Newman-VM-2.1.3. dropbox link is broken

### ISSUE THREAD

**Issue by abh3hu** [Sotera/newman#113]
I followed through the quick start tutorial and did the following.

1) Installed Vagrant 1.9.2
2) Installed Virtualbox 5.1.14
a. Vagrant 1.9.2 and Virtualbox 5.1.14 are compatible (https://www.vagrantup.com/docs/virtualbox/)
3) Install cygwin (ssh client)
4) Tried downloading Newman-VM-2.1.3 but link was broken (https://www.dropbox.com/s/8680d2fjtu96tgw/newman-vm-v2.1.3.box?dl=0) 
a. downloaded zip (https://github.com/Sotera/newman/zipball/master) and extracted at C:\Users\jsmith\virtualboxvms\. Code is version 2.0.0 from zip
5) Typed the following:
a. vagrant init newman-vm-v2.1.3 newman-vm-v2.1.3.box
b. vagrant up

Then I got this error 
![newman github](https://cloud.githubusercontent.com/assets/5413658/23660383/423329fe-0317-11e7-8149-94c70beafbda.JPG)

I also tried changing the command to 
`vagrant init newman-vm-v2.0.0 newman-vm-v2.0.0.box`
but this did not work either

**Comment by smahoney58** [comment]
Fixed broken link, the instructions in the Quick Start should now work.

**Comment by abh3hu** [comment]
I am following the Quick start but cant start my virtual image. 
I read through and followed https://github.com/Sotera/newman/issues/109 and installed Vagrant 1.7.4/VirtualBox 4.3.24.
But I got the error below. I am not sure if the issue is with the box itself or configurations. 

![newman timeout](https://cloud.githubusercontent.com/assets/5413658/23719557/e353e07e-0409-11e7-8d55-7055fd53c6dc.JPG)


Here are the changes I made while trying to make the Quick Start work.
- Changed Bios to allow VTx and VTd 
- Changed config.vm.boot_timeout = 1000
- tried changing username and password to 
`  #config.ssh.username = "root"`
`  #config.ssh.password = "vagrant"`

**Comment by smahoney58** [comment]
Try setting #config.ssh.username = "vagrant". If that doesn't work, I'll have to get a developer involved. I verified that the VirtualBox image downloaded from DropBox is good and successfully ingested a pst file. I use git's ssh client in my setup/installation.

**Comment by abh3hu** [comment]
I switch to using git (1.9.5) for my ssh client and added it to my environment path.
I've also changed the username back to "vagrant" but I still cannot connect.

![newman with git](https://cloud.githubusercontent.com/assets/5413658/23721219/11f9251a-040f-11e7-9d60-45406efbd5c8.JPG)

**Comment by smahoney58** [comment]
Sent an email to the developers. To me it looks like you have ports blocked. When the vagrant up command works, you get a bunch of ports forwarded

![image](https://cloud.githubusercontent.com/assets/10210676/23721797/a2a8b3f2-0408-11e7-9049-1e09c4f3a505.png)

**Comment by abh3hu** [comment]
I checked the first download link I used and I downloaded newman-vm-2.1.1 instead of newman-vm-2.1.3.

I uninstalled and reinstalled everything( Installed Vagrant 1.9.2, Installed Virtualbox 5.1.14, using cygwin as ssh client).
I changed the network ipv4 address from 192.168.56.1 to 192.168.20.1
Everything works now.
